[package]
name = "configurer"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
clap_complete = "4.5.50"
handlebars = "6.3.2"

[build-dependencies]
clap = { version = "4.5.38", features = ["derive"] }
clap_complete = "4.5.50"
